Change design of directions card on MentorsPage and add Fonts to Tailwind Config
catbytes-community/webplatform-frontend pull request #43
Opened 2024-11-21 12:18 UTC by anautomnee

2024-11-21 17:21 UTC, anautomnee commented
> А чего таска 16? А не 43? А так вроде по 43 все прекрасно)

А это моя предыдущая таска, которую я случайно на этой же ветке сделала и Марина должна ее посмотреть 😁

2024-11-28 08:37 UTC, marinacatbytes requested changes
Hi @anautomnee, amazing job!
Just few minor comments and one general - please make smaller PRs, 1 PR for 1 ticket ideally :D :D :D

2024-11-28 12:01 UTC, anautomnee commented on src/pages/AllProjectsPage/ProjectCard/ui/ProjectCard.tsx
> +                        <p className="underline font-bold">SIGN IN <span></span></p>
I have changed to to See details button, but I can still see "Sign in" on other screen in Figma

2024-11-28 12:10 UTC, marinacatbytes approved these changes

2024-11-29 07:25 UTC, merged